#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

echo "---> Downloading dependencies..."
go mod download

echo "---> Building application source..."
go build -v -o main
go install main

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./